site_name: LynxDB 数据库官网

site_url: https://lynxdb.bailizhang.com/

repo_url: https://github.com/LynxDB-Project/lynxdb-docs
edit_uri: edit/main/docs/

nav:
  - 简介: index.md
  - Java 客户端: java_client.md
  - Socket 框架: socket.md
  - Spring Boot: spring_boot.md
  - Arena 内存管理: arena.md
  - 命令行: cmd.md
  - 源码相关: source.md
  - 文件格式: file_format.md
  - 感谢捐赠: donate.md

theme:
  name: readthedocs
  locale: zh_CN
  highlightjs: true
  hljs_languages:
    - java

site_description: LynxDB 是一个轻量级的、由 Java 语言编写的、基于（键，列族，列，值）的数据结构的、高性能的数据库。

site_author: Baili Zhang

copyright: <p><b>欢迎捐赠：</b>请备注捐赠人称呼，将会在捐赠页面展示。</p><p>支付宝：<img src="/img/alipay.jpg" alt="支付宝" /></p><p>微信：<img src="/img/wechat_pay.jpg" alt="微信" /></p><p>Copyright &copy; 2023 <a href="/">bailizhang.com</a></p><p>备案号：<a href="https://beian.miit.gov.cn">沪ICP备2023018496号-1</a></p>

extra_css:
  - css/style.css
