site_name: LynxDB 数据库

site_url: https://lynxdb.bailizhang.com/

repo_url: https://github.com/LynxDB-Project/lynxdb-docs.git

nav:
  - 简介: intro.md
  - Java 客户端: java_client.md
  - Spring Boot: spring_boot.md
  - 命令行: cmd.md
  - 源码相关: source.md
  - 文件格式: file_format.md

theme:
  name: readthedocs
  locale: zh_CN
  highlightjs: true
  hljs_languages:
    - java

site_description: LynxDB 是一个轻量级的、由 Java 语言编写的、基于（键，列族，列，值）的数据结构的、高性能的数据库。

site_author: Baili Zhang

copyright: <p>Copyright &copy; 2023 <a href="/">bailizhang.com</a></p><p>备案号：<a href="https://beian.miit.gov.cn">沪ICP备2023018496号-1</a></p>

extra_css:
  - css/style.css
